In [1]:
pip install numpy  #to install


Note: you may need to restart the kernel to use updated packages.


ERROR: Invalid requirement: '#to'


In [4]:
import numpy as np  #import numpy library

In [5]:
a=np.array([1,2,3])

In [6]:
print(a)

[1 2 3]


In [7]:
c=np.array([(4,5,6),(1,2,3)])

In [8]:
print(c)

[[4 5 6]
 [1 2 3]]


In [9]:
b=np.array([(11,23,45,67)])

In [10]:
b

array([[11, 23, 45, 67]])

In [11]:
trans1=np.transpose(c)  #tranpose a value

In [12]:
trans1

array([[4, 1],
       [5, 2],
       [6, 3]])

In [13]:
trans=np.transpose(b)

In [14]:
trans

array([[11],
       [23],
       [45],
       [67]])

In [15]:
trans1.ravel()

array([4, 1, 5, 2, 6, 3])

In [16]:
trans.ravel()  #tranpoesd value into single line

array([11, 23, 45, 67])

In [17]:
a

array([1, 2, 3])

In [18]:
a.reshape(3,1)  #to use roes in colum # first nymber define rows second number define column

array([[1],
       [2],
       [3]])

In [38]:
ze=np.zeros((3,3))

In [39]:
ze

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
ze.resize(3,2)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [35]:

ze

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.append(trans,ze) # to add a value

array([11., 23., 45., 67.,  0.,  0.,  0.])

In [41]:
ins=np.insert(a,2,7)  #insert speific value in array (arrayname,inde,insert value)

In [42]:
ins

array([1, 2, 7, 3])

In [44]:
dels=np.delete(a,[1])

In [45]:
dels

array([1, 3])

In [47]:
txt=np.array([(1,2),(5,8)])

In [49]:
txt


array([[1, 2],
       [5, 8]])

In [52]:
np.concatenate((txt,txt),axis=None)



array([1, 2, 5, 8, 1, 2, 5, 8])

In [53]:
np.hstack((txt,txt))  #harizontal vise 


array([[1, 2, 1, 2],
       [5, 8, 5, 8]])

In [54]:
np.vstack((txt,txt)) #vertical vise 

array([[1, 2],
       [5, 8],
       [1, 2],
       [5, 8]])

In [57]:
np.vsplit(txt,2)

[array([[1, 2]]), array([[5, 8]])]